N_way: ${data.test_class_num}  # ğŸ”¥ é‡ç‚¹åœ¨è¿™é‡Œ
K_shot: 10
query_size: 10
P_num_task: 10
use_sampler_augmentation: false  # æ§åˆ¶æ˜¯å¦ä½¿ç”¨æ•°æ®å¢å¼ºï¼ˆtrueå¯ç”¨ï¼Œfalseç¦ç”¨ï¼‰
num_epochs: 1000